#!/bin/bash

# You can call this script like this:
# $./changeVolume up
# $./changeVolume down
# $./changeVolume mute

msg_tag="changeVolume"

function get_volume {
    amixer -D pulse get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
    amixer -D pulse get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function send_notification {
    volume=`get_volume`
    if [ "$volume" = "0" ]; then
        icon_name="notification-audio-volume-off"
    else
        if [  "$volume" -lt "33" ]; then
            icon_name="notification-audio-volume-low"
        else
            if [ "$volume" -lt "67" ]; then
                icon_name="notification-audio-volume-medium"
            else
                icon_name="notification-audio-volume-high"
            fi
        fi
    fi
    bar=$(seq -s "█" $(($volume/5)) | sed 's/[0-9]//g')
    dunstify -a $msg_tag -i $icon_name -h string:x-dunst-stack-tag:$msg_tag "     $bar"
}

case $1 in
    up)
	amixer -D pulse set Master on > /dev/null
	amixer -D pulse sset Master 5%+ > /dev/null
	send_notification
	;;
    down)
	amixer -D pulse set Master on > /dev/null
	amixer -D pulse sset Master 5%- > /dev/null
	send_notification
	;;
    mute)
	amixer -D pulse set Master 1+ toggle > /dev/null
	if is_mute ; then
        dunstify -a $msg_tag -i "notification-audio-volume-muted" -h string:x-dunst-stack-tag:$msg_tag ""
	else
	    send_notification
	fi
	;;
esac
