#!/bin/bash

# You can call this script like this:
# $./changeBrightness up
# $./changeBrightness down

msg_tag="changeBrightness"

function get_brightness {
    light | cut -d "." -f 1
}

function send_notification {
    brightness=`get_brightness`
    if [ "$brightness" = "100" ]; then
        icon_name="notification-display-brightness-full"
    else
        if [  "$brightness" -lt "33" ]; then
            icon_name="notification-display-brightness-low"
        else
            if [ "$brightness" -lt "67" ]; then
                icon_name="notification-display-brightness-medium"
            else
                icon_name="notification-display-brightness-high"
            fi
        fi
    fi
    bar=$(seq -s "─" $(($brightness/5)) | sed 's/[0-9]//g')
    dunstify -a $msg_tag -i $icon_name -h string:x-dunst-stack-tag:$msg_tag "     $bar"
}

case $1 in
    up)
	light -A 5 > /dev/null
	send_notification
	;;
    down)
	light -U 5 > /dev/null
	send_notification
	;;
esac
