#!/usr/bin/env python3

import dbus
import sys

bus = dbus.SessionBus()
obj = bus.get_object('org.clight.clight','/org/clight/clight')

if sys.argv[1] == '-inc':
	obj.IncBl(float(sys.argv[2]),dbus_interface='org.clight.clight')
if sys.argv[1] == '-dec':
	obj.DecBl(float(sys.argv[2]),dbus_interface='org.clight.clight')