#!/bin/python3

from random import sample
from pathlib import Path
import textwrap

width = 50

with open(Path(__file__).parent / "iroh_quotes.txt", "r") as file:
    quote = sample(file.readlines(), 1)[0]

quote = quote.replace("\n", " ").strip()
lines = textwrap.wrap(quote, width=width)

print("\n".join(lines) + "\n\n- Uncle Iroh")
