#!/usr/bin/env bash

PICTURE=~/.config/wallpapers/gruvbox10.png
# SCREENSHOT="scrot -z $PICTURE"

BLUR="0x10"
BLANK='#00000000'
BACKGROUND="#282828"
BACKGROUND_HARD="#1D2021"
BACKGROUND_SOFT="#32302F"
BACKGROUND_1="#3C3836"
BACKGROUND_2="#504945"
BACKGROUND_3="#665C54"
BACKGROUND_4="#7C6F64"
FOREGROUND="#EBDBB2"
FOREGROUND_HARD="#FBF1C7"
FOREGROUND_SOFT="#FBF1C7"
FOREGROUND_1="#EBDBB2"
FOREGROUND_2="#D5C4A1"
FOREGROUND_3="#BDAE93"
FOREGROUND_4="#A89984"
RED_HARD="#CC241D"
RED_SOFT="#FB4934"
GREEN_HARD="#98971A"
GREEN_SOFT="#B8BB26"
YELLOW_HARD="#D79921"
YELLOW_SOFT="#FABD2F"
BLUE_HARD="#458588"
BLUE_SOFT="#83A598"
PURPLE_HARD="#B16286"
PURPLE_SOFT="#D3869B"
AQUA_HARD="#689D6A"
AQUA_SOFT="#8EC07C"
ORANGE_HARD="#D65D0E"
ORANGE_SOFT="#FE8019"

# $SCREENSHOT
# convert $PICTURE -blur $BLUR $PICTURE
i3lock --nofork                     \
 -i $PICTURE -e                     \
--ringver-color=$GREEN_HARD         \
--ringwrong-color=$RED_SOFT         \
--ring-color=$FOREGROUND_SOFT       \
--separator-color=$FOREGROUND_SOFT  \
--verif-color=$FOREGROUND           \
--wrong-color=$FOREGROUND           \
--keyhl-color=$YELLOW_SOFT          \
--bshl-color=$YELLOW_SOFT           \
--line-color=$BLANK                 \
--inside-color=$BLANK               \
--insidewrong-color=$BLANK          \
--insidever-color=$BLANK            \
# rm $PICTURE
